version: '3.8'

services:
  llm:
    build: https://github.com/gianlucatruda/llm-router.git#v0.2.0 # Will use version 0.2.0
    container_name: llm
    # networks: # Must have web access
    env_file:
      - .secrets/llm # OPENAI_API_KEY and ANTHROPIC_API_KEY
    environment:
      - DATABASE_PATH=./data/llm-router.db
    volumes:
      - ${HOMELAB_DATA_DIR}/llm:/app/data
    restart: unless-stopped
